config/routes.rb
Rails.application.routes.draw do
  get 'helps/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  root 'home#index'

  resources :users

  get 'show', to: 'users#show', as: 'show'
  put 'update', to: 'users#update', as: 'update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/district.rb
class District < ApplicationRecord
    belongs_to :state
    has_many :helps
end

app/models/help.rb
class Help < ApplicationRecord
    belongs_to :user, inverse_of: :helps
    belongs_to :district

    enum help_type: [:food, :essentials, :volunteer, :financial]
    validates_presence_of :user
end

app/models/initiative.rb
class Initiative < ApplicationRecord
end

app/models/state.rb
class State < ApplicationRecord
    has_many :districts
end

app/models/user.rb
class User < ApplicationRecord
    has_many :helps, inverse_of: :user
    accepts_nested_attributes_for :helps

    # before_save :valid_phone_number?

    def valid_confirmation_code?(code, country_code, phone_number)
        response = Authy::PhoneVerification.check(verification_code: code, country_code: country_code, phone_number: phone_number)
        response.success?
    end

    def valid_phone_number?
        response = Authy::PhoneVerification.start(country_code: +6, phone_number: self.phone_number)
        response.success?
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user
  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    else
      @current_user = nil
    end
  end
end

app/controllers/helps_controller.rb
class HelpsController < ApplicationController
  def show
    @help = Help.find(params[:format])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @helps =
        # if user selects both help type & area
        if (params[:helps_search] != "" && params[:helps_search] != nil) && (params[:districts_search] != "" && params[:districts_search] != nil)
            Help.where({help_type: params[:helps_search]} && {district_id: params[:districts_search]})
        # if user  only selects help type 
        elsif (params[:helps_search] != "") && (params[:districts_search] == "")
            Help.where({help_type: params[:helps_search]})
        # if user only selects districts
        elsif (params[:helps_search] == "") && (params[:districts_search] != "")
            Help.where({district_id: params[:districts_search]})
        else
            Help.all
        end

        @initiatives = Initiative.all
        @states = State.all
    end
    
end

app/controllers/initiatives_controller.rb
class InitiativesController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController  
    def new
       @user = User.new
       @user.helps.new
    end

    def create
      @user = User.create!(user_params)
      if @user.valid_phone_number?
        @user.save
        session[:user_id] = @user.id
        redirect_to edit_user_path(@user.id)
      else
        render 'new'
      end
    end
    
    def show
      @user = current_user
    end
    
    def edit
      @user = current_user
    end
    
    def update
      @user = current_user
      if @user.valid_confirmation_code?(code_params["code"], +60, @user.phone_number)
        @user.update(verified: true)
        puts 'Your number is verified!'
        redirect_to root_path
      else
        render 'edit'
      end
    end
    
    private

    def user_params
      params.require(:user).permit(:name, :phone_number, helps_attributes: [:district_id,:help_type,:description])
    end

    def code_params
      params.require(:user).permit(:code)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/helps_helper.rb
module HelpsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/initiatives_helper.rb
module InitiativesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/helps/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>help</title>
</head>
<body>
    <h3 class="heading"><%= @help.user.name %></h3>
    <p class="subheading"><%= @help.district.name %>, <%= @help.district.state.name %></p>
    <p class="paragraph"><%= @help.description %></p>
    <%= link_to 'Contact', "https://wa.me/60#{@help.user.phone_number}", target: "_blank", class: "primary" %>
</body>
</html>

app/views/home/_flash_msg.html.erb
<div class="no-results-msg .subheading">
    There are no results with this criteria. If you or someone you know needs help, feel free to <%= link_to 'get help', new_user_path %>
</div>

app/views/home/_helps.html.erb
<div class="swiper-container swiper1">
    <div class="swiper-wrapper">
        <% @helps.each do |help| %>
            <div class="swiper-slide">
                <div class="card">
                    <div class="card-text">
                        <p class="card-heading"><%= help.user.name %></p>
                        <p class="tag"><%= help.help_type %></p>         
                        <p class="card-subheading"><%= help.district.name %>, <%= help.district.state.name %></p>
                        <p class="card-paragraph"><%= help.description %></p>
                    </div>
                    <%= link_to 'Help', "https://wa.me/60#{help.user.phone_number}", target: "_blank", class: "card-link" %>
                </div>
            </div>
        <% end %>
    </div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-pagination"></div>
</div>

app/views/home/_initiatives.html.erb
<div class="swiper-container swiper2">
    <div class="swiper-wrapper">
        <% @initiatives.each do |initiative| %>
            <div class="swiper-slide">
                <div class="card">
                    <%# <div class="card-img"></div> %>
                    <div class="card-text">
                        <p class='card-heading'><%= initiative.name %></p>
                        <p class="tag"><%= initiative.help_needed %></p>
                        <div class="card-paragraph"><%= initiative.description %></div>
                    </div>
                    <%= link_to 'Help', initiative.link, target: '_blank', class: 'card-link' %>
                </div>
            </div>
        <% end %>
    </div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
    <div class="swiper-pagination"></div>
</div>

app/views/home/_users.html.erb
<div class="swiper-container swiper1">
    <div class="swiper-wrapper">
        <% @users.each do |user| %>
            <div class="swiper-slide">
                <div class="card">
                    <div class="card-img"></div>
                    <div class="card-text">
                        <p class="tag"><%= user.helps.last.help_type %></p>         
                        <p class="card-heading"><%= user.name %></p>
                        <p class="card-subheading"><%= user.helps.last.district.name %>, <%= user.helps.last.district.state.name %></p>
                        <p class="card-paragraph"><%= user.helps.last.description %></p>
                    </div>
                    <a class="card-link">Help</a>
                </div>
            </div>
        <% end %>
    </div>
    <div class="swiper-button-prev"></div>
    <div class="swiper-button-next"></div>
</div>

app/views/home/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>jom tolong</title>
</head>
<body>
    <section id="hero">
        <div class="hero-copy">
            <h1 class="heading">Help is needed.</h1>
            <div class="subheading">Let's connect those who need help to those who can help</div>
        </div>
        <div class="hero-links">
            <%= link_to 'I need help', new_user_path, class: "primary paragraph" %>
        </div>
        <div class="photo-credit">Photo by <a href="https://www.pexels.com/@ihsanaditya?utm_content=attributionCopyText&utm_medium=referral&utm_source=pexels">Ihsan Aditya</a> from <a href="https://www.pexels.com/photo/flag-of-malaysia-3011004/?utm_content=attributionCopyText&utm_medium=referral&utm_source=pexels">Pexels</a></div>
    </section>
    
    <section id="filter">
        <h2 class="subheading">I can help</h2>
        <%= form_with url: root_path, method: 'GET' do |form| %>
            <div class="with">
                <%= form.label 'with', class: 'paragraph' %>
                <%= form.select :helps_search, options_for_select(Help.help_types.keys), include_blank: true %>
            </div>
            <div class="state">
                <%= form.label 'state', class: 'paragraph' %>
                <%= form.collection_select :state_search, State.order(:name), :name, :name, include_blank: true %>
            </div>
            <div class="area">
                <%= form.label 'area', class: 'paragraph' %>
                <%= form.grouped_collection_select :districts_search, State.order(:name), :districts, :name, :id, :name, include_blank: true %>
            </div>

            <%= form.submit 'Filter' %>
        <% end %>
    </section>

    <section id="help-section">
        <h2 class='subheading'>People who need your help...</h2>
        <div id="helps-partial">
            <% if @helps.blank? %>
                <%= render partial: 'flash_msg' %>
            <% else %> 
                <%= render partial: 'helps' %>
            <% end %>
        </div>
    </section>

    <section id="initiatives">
        <h2 class='subheading'>Initiatives who need your help...</h2>
        <div id="initiatives-partial">
            <%= render partial: 'initiatives' %>
        </div>
    </section>

    <%= javascript_pack_tag 'home' %>
</body>
</html>

app/views/home/index.js.erb
<%# Partials %>
var help_partial = document.getElementById('helps-partial');


<% if @helps.blank? %>
	help_partial.innerHTML = "<%= j (render partial: 'flash_msg') %>";
<% else %>
	help_partial.innerHTML = "<%= j (render partial: 'helps') %>";
<% end %>


var swiper1 = new Swiper ('.swiper1', {
            direction: 'horizontal',
            loop: 'false',
            centeredSlides: 'true',
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            pagination: {
		          el: '.swiper-pagination'
            },
            breakpoints: {
              500: {
                slidesPerView: 2,
                spaceBetween: 140
              },
              575: {
                slidesPerView: 2,
                spaceBetween: 100
              },
              767: {
                slidesPerView: 3,
                spaceBetween: 200
              },
              992: {
                slidesPerView: 4,
                spaceBetween: 245
              },
              1200: {
                slidesPerView: 5,
                spaceBetween: 270
              }
            }
        })

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JomTolong</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://unpkg.com/swiper/css/swiper.min.css' %>
    <%= stylesheet_link_tag 'https://fonts.googleapis.com/css2?family=Asap:wght@400;700&display=swap' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="logo">
        <%= image_tag 'logo.png' %>
      </div>
    </header>

    <%= yield %>

    <footer>
      <div class="logo">
        <%= image_tag 'logo.png' %>
      </div>
    </footer>

    <%= javascript_include_tag 'https://unpkg.com/swiper/js/swiper.min.js' %>
    <script>
        var swiper1 = new Swiper ('.swiper1', {
            direction: 'horizontal',
            loop: 'false',
            centeredSlides: 'true',
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            pagination: {
		          el: '.swiper-pagination'
            },
            breakpoints: {
              500: {
                slidesPerView: 2,
                spaceBetween: 140
              },
              575: {
                slidesPerView: 2,
                spaceBetween: 100
              },
              767: {
                slidesPerView: 3,
                spaceBetween: 200
              },
              992: {
                slidesPerView: 4,
                spaceBetween: 245
              },
              1200: {
                slidesPerView: 5,
                spaceBetween: 270
              }
            }
        })

        var swiper2 = new Swiper ('.swiper2', {
            direction: 'horizontal',
            loop: 'false',
            centeredSlides: 'true',
            navigation: {
                nextEl: '.swiper-button-next',
                prevEl: '.swiper-button-prev',
            },
            pagination: {
		          el: '.swiper-pagination'
            },
            breakpoints: {
              500: {
                slidesPerView: 2,
                spaceBetween: 140
              },
              575: {
                slidesPerView: 2,
                spaceBetween: 100
              },
              767: {
                slidesPerView: 3,
                spaceBetween: 200
              },
              992: {
                slidesPerView: 4,
                spaceBetween: 245
              },
              1200: {
                slidesPerView: 5,
                spaceBetween: 270
              }
            }
        })
    </script>
  </body>
</html>

app/views/persons_in_need/new.html.erb
<h3>Fill in your information</h3>

<%= form_with model: @person_in_need, url: persons_in_need_index_path do |form| %>
    <%= form.label :name %>
    <%= form.text_field :name %>
    <br>
    <%= form.label :phone_number %>
    <%= form.text_field :phone_number %>
    <br>
    <%= form.fields_for :helps do |help_form| %>
        <%= help_form.label :district_id %>
        <%= help_form.grouped_collection_select :district_id, State.order(:name), :districts, :name, :id, :name, include_blank: true %>
        <br>
        <%= help_form.label 'What kind of help do you need?' %>
        <%= help_form.select :help_type, options_for_select(Help.help_types.keys), include_blank: true %>
        <br>
        <%= help_form.label 'Describe' %>
        <%= help_form.text_area :description %>
    <% end %>
    <%= form.submit 'Post' %>
<% end %>

app/views/users/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Edit</title>
</head>
<body>
    <%= form_with model: @user do |form| %>
    <h3>Enter your verification code</h3>
    <p>A verification code will be sent to you shortly.</p>
        <%= form.label :code %>
        <%= form.text_field :code %>
        <%= form.submit 'Verify', url: update_path(@user) %>
    <% end %>
</body>
</html>

app/views/users/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <%= form_with model: @user do |form| %>
        <h3 class='subheading'>Fill in your information</h3>
        <p class='paragraph'>Your request will be posted, anyone who wants to help you will be able to contact you directly via Whatsapp.</p>
        <%= form.label :name, class: 'paragraph' %>
        <%= form.text_field :name %>
        <br>
        <%= form.label :phone_number, class: 'paragraph' %>
        <%= form.text_field :phone_number %>
        <br>
        <%= form.fields_for :helps do |help_form| %>
            <%= help_form.fields_for :districts do |f| %>
                <%= f.label :state, class: 'paragraph' %>
                <%= f.collection_select :state_id, State.order(:name), :name, :name, include_blank: true %>
            <% end %>
            <%= help_form.label :district_id, class: 'paragraph' %>
            <%= help_form.grouped_collection_select :district_id, State.order(:name), :districts, :name, :id, :name, include_blank: true %>
            <br>
            <%= help_form.label 'What kind of help do you need?', class: 'paragraph' %>
            <%= help_form.select :help_type, options_for_select(Help.help_types.keys), include_blank: true %>
            <br>
            <%= help_form.label 'Describe', class: 'paragraph' %>
            <%= help_form.text_area :description %>
        <% end %>
        <%= form.submit 'Post', class: "primary paragraph" %>
    <% end %>

    <%= javascript_pack_tag 'new' %>
</body>
</html>